### ISSUE TITLE
Indentation of LICENSE file

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/repo-templates#18]
Out of curiosity, why does the LICENSE file include 4 spaces of indentation? Is there any kind of standard that suggests this or reason it was done?

**Comment by jeffwilcox** [comment]
Wild. Never noticed this.

I think we don't have a great story for you... someone probably drafted a version once and it's been copied a bunch since.

**Comment by adamjstewart** [comment]
Cool, just curious, it's still correctly auto-detected so I think it's harmless. Might unindent it in https://github.com/microsoft/torchgeo
